### ISSUE TITLE
Project not compiling

### ISSUE THREAD

**Issue by josephraj2k16** [HossamElghamry/Medicine-Reminder#4]
hi,I have downloaded your project from github,extracted it and ran it.It shows a following error.Can you help me out?

Error message:

Compiler message:
file:///C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flare_flutter-1.5.4/lib/flare.dart:1027:18: Error: The argument type 'Uint16List' can't be assigned to the parameter type 'Int32List'.
 - 'Uint16List' is from 'dart:typed_data'.
 - 'Int32List' is from 'dart:typed_data'.
Try changing the type of the parameter, or casting the argument to 'Int32List'.
        indices: _indices, textureCoordinates: _uvBuffer);
                 ^
Compiler failed on C:\Users\test\Desktop\software\HossamElghamry-Mediminder-53684f7\lib\main.dart
Finished with error: Gradle task assembleDebug failed with exit code 1

**Comment by HossamElghamry** [comment]
Dear Joseph,
Please try to upgrade Flutter by executing the following command lines:

$ flutter channel stable
$ flutter upgrade

The error happens because of a breaking change in Flare, making it incompatible with the current Flutter version you are using. Upgrading your Flutter framework on the stable channel should solve the problem.
